### ISSUE TITLE
关于理论上一个contract最多可保存的字节数

### ISSUE THREAD

**Issue by Neronjust2017** [ABCDELabs/Understanding-Ethereum-Go-version#18]
hi, 大佬你好，最近在阅读你写的这本书。chapter 3 账户和合约中有这么一段话：

![image](https://github.com/ABCDELabs/Understanding-Ethereum-Go-version/assets/27863360/b6a394f0-9896-4fa8-b6dc-c92f9c3536df)

这里一个 Contract 可以最多保存的数据是否应该是 (2^256 - 1) * 32？

**Comment by hsyodyssey** [comment]
对的，好像这是个排版时候的Typo，我检查一下，感谢提醒🙏。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Neronjust2017 ***@***.***>
发送时间: Sunday, June 11, 2023 4:00:04 PM
收件人: ABCDELabs/Understanding-Ethereum-Go-version ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ABCDELabs/Understanding-Ethereum-Go-version] 关于理论上一个contract最多可保存的字节数 (Issue #18)


hi, 大佬你好，最近在阅读你写的这本书。chapter 3 账户和合约中有这么一段话：

[image]<https://user-images.githubusercontent.com/27863360/244922646-b6a394f0-9896-4fa8-b6dc-c92f9c3536df.png>

这里一个 Contract 可以最多保存的数据是否应该是 (2^256 - 1) * 32？

**Comment by Neronjust2017** [comment]
另外，请问完整版本预计什么时候出来？这本书对了解以太坊的工程代码实现细节十分有帮助，十分期待拜读完整版！

**Comment by hsyodyssey** [comment]
感谢支持🙏，我们会持续风险。预计Q3会有一个相对完整的版本。
